image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      touch /tmp/.yarn-lock
      yarn install
      rm /tmp/.yarn-lock
  - init: sleep 1 && while [ -f /tmp/.yarn-lock ]; do sleep 1; done
    command: yarn start
ports:
  - port: 3000
    onOpen: open-preview
